name: Bug Report
description: Report a bug in ObjectDocs
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Run `objectdocs build`
        2. Navigate to ...
        3. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen.
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: ObjectDocs Version
      description: "Run `objectdocs --version` to find this."
      placeholder: "e.g., 0.2.12"
    validations:
      required: true
  - type: dropdown
    id: package
    attributes:
      label: Package
      description: Which package is affected?
      options:
        - "@objectdocs/cli"
        - "@objectdocs/site"
        - Both
    validations:
      required: true
  - type: input
    id: node-version
    attributes:
      label: Node.js Version
      placeholder: "e.g., 22.x"
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - macOS
        - Linux
        - Windows
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or log output about the problem.
