name: Documentation Feedback
description: Report an issue with the documentation or suggest improvements
title: "[Docs]: "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Help us improve our documentation! Report errors, suggest additions, or request clarifications.
  - type: dropdown
    id: type
    attributes:
      label: Feedback Type
      options:
        - Error or Inaccuracy
        - Missing Information
        - Improvement Suggestion
        - New Page Request
        - Translation Issue
    validations:
      required: true
  - type: input
    id: page-url
    attributes:
      label: Page URL
      description: Link to the page with the issue (if applicable).
      placeholder: "https://objectdocs.com/docs/..."
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the issue or suggestion.
    validations:
      required: true
  - type: textarea
    id: suggested-change
    attributes:
      label: Suggested Change
      description: If you have a specific fix or improvement in mind, describe it here.
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or references.
